name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'examples/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'examples/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm i -g pnpm@6

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-ubuntu-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Unit test
        run: pnpm test:unit

      - name: End-to-end test
        uses: cypress-io/github-action@v2
        with:
          headless: true
          start: pnpm cy:setup
          wait-on: 'http://localhost:10003'
          install: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
